package com.societatis.util;

import java.util.ArrayList;
import java.util.List;

public class CountryList {
	private List<String> Countries = new ArrayList<String>();

	public List<String> getCountryList() {

		Countries.add("Afghanistan");
		Countries.add("Aland Islands (Finland)");
		Countries.add("Albania");
		Countries.add("Algeria");
		Countries.add("American Samoa (USA)");
		Countries.add("Andorra");
		Countries.add("Angola");
		Countries.add("Anguilla (UK)");
		Countries.add("Antigua and Barbuda");
		Countries.add("Argentina");
		Countries.add("Armenia");
		Countries.add("Aruba (Netherlands)");
		Countries.add("Australia");
		Countries.add("Austria");
		Countries.add("Azerbaijan");
		Countries.add("Bahamas");
		Countries.add("Bahrain");
		Countries.add("Bangladesh");
		Countries.add("Barbados");
		Countries.add("Belarus");
		Countries.add("Belgium");
		Countries.add("Belize");
		Countries.add("Benin");
		Countries.add("Bermuda (UK)");
		Countries.add("Bhutan");
		Countries.add("Bolivia");
		Countries.add("Bosnia and Herzegovina");
		Countries.add("Botswana");
		Countries.add("Brazil");
		Countries.add("British Virgin Islands (UK)");
		Countries.add("Brunei");
		Countries.add("Bulgaria");
		Countries.add("Burkina Faso");
		Countries.add("Burma");
		Countries.add("Burundi");
		Countries.add("Cambodia");
		Countries.add("Cameroon");
		Countries.add("Canada");
		Countries.add("Cape Verde");
		Countries.add("Caribbean Netherlands (Netherlands)");
		Countries.add("Cayman Islands (UK)");
		Countries.add("Central African Republic");
		Countries.add("Chad");
		Countries.add("Chile");
		Countries.add("China");
		Countries.add("Christmas Island (Australia)");
		Countries.add("Cocos (Keeling) Islands (Australia)");
		Countries.add("Colombia");
		Countries.add("Comoros");
		Countries.add("Cook Islands (NZ)");
		Countries.add("Costa Rica");
		Countries.add("Croatia");
		Countries.add("Cuba");
		Countries.add("Curacao (Netherlands)");
		Countries.add("Cyprus");
		Countries.add("Czech Republic");
		Countries.add("Democratic Republic of the Congo");
		Countries.add("Denmark");
		Countries.add("Djibouti");
		Countries.add("Dominica");
		Countries.add("Dominican Republic");
		Countries.add("Ecuador");
		Countries.add("Egypt");
		Countries.add("El Salvador");
		Countries.add("Equatorial Guinea");
		Countries.add("Eritrea");
		Countries.add("Estonia");
		Countries.add("Ethiopia");
		Countries.add("Falkland Islands (UK)");
		Countries.add("Faroe Islands (Denmark)");
		Countries.add("Federated States of Micronesia");
		Countries.add("Fiji");
		Countries.add("Finland");
		Countries.add("France");
		Countries.add("French Guiana (France)");
		Countries.add("French Polynesia (France)");
		Countries.add("Gabon");
		Countries.add("Gambia");
		Countries.add("Georgia");
		Countries.add("Germany");
		Countries.add("Ghana");
		Countries.add("Gibraltar (UK)");
		Countries.add("Greece");
		Countries.add("Greenland (Denmark)");
		Countries.add("Grenada");
		Countries.add("Guadeloupe (France)");
		Countries.add("Guam (USA)");
		Countries.add("Guatemala");
		Countries.add("Guernsey (UK)");
		Countries.add("Guinea");
		Countries.add("Guinea-Bissau");
		Countries.add("Guyana");
		Countries.add("Haiti");
		Countries.add("Honduras");
		Countries.add("Hong Kong (China)");
		Countries.add("Hungary");
		Countries.add("Iceland");
		Countries.add("India");
		Countries.add("Indonesia");
		Countries.add("Iran");
		Countries.add("Iraq");
		Countries.add("Ireland");
		Countries.add("Isle of Man (UK)");
		Countries.add("Israel");
		Countries.add("Italy");
		Countries.add("Ivory Coast");
		Countries.add("Jamaica");
		Countries.add("Japan");
		Countries.add("Jersey (UK)");
		Countries.add("Jordan");
		Countries.add("Kazakhstan");
		Countries.add("Kenya");
		Countries.add("Kiribati");
		Countries.add("Kosovo");
		Countries.add("Kuwait");
		Countries.add("Kyrgyzstan");
		Countries.add("Laos");
		Countries.add("Latvia");
		Countries.add("Lebanon");
		Countries.add("Lesotho");
		Countries.add("Liberia");
		Countries.add("Libya");
		Countries.add("Liechtenstein");
		Countries.add("Lithuania");
		Countries.add("Luxembourg");
		Countries.add("Macau (China)");
		Countries.add("Macedonia");
		Countries.add("Madagascar");
		Countries.add("Malawi");
		Countries.add("Malaysia");
		Countries.add("Maldives");
		Countries.add("Mali");
		Countries.add("Malta");
		Countries.add("Marshall Islands");
		Countries.add("Martinique (France)");
		Countries.add("Mauritania");
		Countries.add("Mauritius");
		Countries.add("Mayotte (France)");
		Countries.add("Mexico");
		Countries.add("Moldov");
		Countries.add("Monaco");
		Countries.add("Mongolia");
		Countries.add("Montenegro");
		Countries.add("Montserrat (UK)");
		Countries.add("Morocco");
		Countries.add("Mozambique");
		Countries.add("Namibia");
		Countries.add("Nauru");
		Countries.add("Nepal");
		Countries.add("Netherlands");
		Countries.add("New Caledonia (France)");
		Countries.add("New Zealand");
		Countries.add("Nicaragua");
		Countries.add("Niger");
		Countries.add("Nigeria");
		Countries.add("Niue (NZ)");
		Countries.add("Norfolk Island (Australia)");
		Countries.add("North Korea");
		Countries.add("Northern Mariana Islands (USA)");
		Countries.add("Norway");
		Countries.add("Oman");
		Countries.add("Pakistan");
		Countries.add("Palau");
		Countries.add("Palestine");
		Countries.add("Panama");
		Countries.add("Papua New Guinea");
		Countries.add("Paraguay");
		Countries.add("Peru");
		Countries.add("Philippines");
		Countries.add("Pitcairn Islands (UK)");
		Countries.add("Poland");
		Countries.add("Portugal");
		Countries.add("Puerto Rico");
		Countries.add("Qatar");
		Countries.add("Republic of the Congo");
		Countries.add("Reunion (France)");
		Countries.add("Romania");
		Countries.add("Russia");
		Countries.add("Rwanda");
		Countries.add("Saint Barthelemy (France)");
		Countries.add("Saint Kitts and Nevis");
		Countries.add("Saint Lucia");
		Countries.add("Saint Martin (France)");
		Countries.add("Saint Pierre and Miquelon (France)");
		Countries.add("Saint Vincent and the Grenadines");
		Countries.add("Samoa");
		Countries.add("San Marino");
		Countries.add("Sao Tom and Principe");
		Countries.add("Saudi Arabia");
		Countries.add("Senegal");
		Countries.add("Serbia");
		Countries.add("Seychelles");
		Countries.add("Sierra Leone");
		Countries.add("Singapore");
		Countries.add("Sint Maarten (Netherlands)");
		Countries.add("Slovakia");
		Countries.add("Slovenia");
		Countries.add("Solomon Islands");
		Countries.add("Somalia");
		Countries.add("South Africa");
		Countries.add("South Korea");
		Countries.add("South Sudan");
		Countries.add("Spain");
		Countries.add("Sri Lanka");
		Countries.add("Sudan");
		Countries.add("Suriname");
		Countries.add("Svalbard and Jan Mayen (Norway)");
		Countries.add("Swaziland");
		Countries.add("Sweden");
		Countries.add("Switzerland");
		Countries.add("Syria");
		Countries.add("Taiwan");
		Countries.add("Tajikistan");
		Countries.add("Tanzania");
		Countries.add("Thailand");
		Countries.add("Timor-Leste");
		Countries.add("Togo");
		Countries.add("Tokelau (NZ)");
		Countries.add("Tonga");
		Countries.add("Trinidad and Tobago");
		Countries.add("Tunisia");
		Countries.add("Turkey");
		Countries.add("Turkmenistan");
		Countries.add("Turks and Caicos Islands (UK)");
		Countries.add("Tuvalu");
		Countries.add("Uganda");
		Countries.add("Ukraine");
		Countries.add("United Arab Emirates");
		Countries.add("United Kingdom");
		Countries.add("United States");
		Countries.add("United States Virgin Islands (USA)");
		Countries.add("Uruguay");
		Countries.add("Uzbekistan");
		Countries.add("Vanuatu");
		Countries.add("Vatican City");
		Countries.add("Venezuela");
		Countries.add("Vietnam");
		Countries.add("Wallis and Futuna (France)");
		Countries.add("Western Sahara");
		Countries.add("Yemen");
		Countries.add("Zambia");
		Countries.add("Zimbabwe");

		return Countries;
		
		
		
	}
	
	
}
