package com.societatis.util;

import java.util.ArrayList;
import java.util.List;

public class MotherTongueList {
	private List<String> Languages = new ArrayList<String>();

	public List<String> getMotherToungueList() {

		
		
		Languages.add("Akan");
		Languages.add("Albanian");
		Languages.add("Amis");
		Languages.add("Arabic");
		Languages.add("Arabic, Algerian Spoken");
		Languages.add("Arabic, Baharna Spoken");
		Languages.add("Arabic, Egyptian Spoken");
		Languages.add("Armenian");
		Languages.add("Australian");
		Languages.add("Azerbaijani, North");
		Languages.add("Bavarian");
		Languages.add("Belarusan");
		Languages.add("Bengali");
		Languages.add("Beti");
		Languages.add("Bosnian");
		Languages.add("Bribi");
		Languages.add("Bube");
		Languages.add("Bulgarian");
		Languages.add("Burmese");
		Languages.add("Carib");
		Languages.add("Central Algonquian");
		Languages.add("Central K'iche' (Mayan)");
		Languages.add("Cherokee");
		Languages.add("Chibchan");
		Languages.add("Comorian");
		Languages.add("Croatian");
		Languages.add("Cusco Quechua");
		Languages.add("Czech");
		Languages.add("Danish");
		Languages.add("Dutch");
		Languages.add("Dzonghka");
		Languages.add("English");
		Languages.add("Estonian");
		Languages.add("Ewe");
		Languages.add("Farsi");
		Languages.add("Fijian");
		Languages.add("Finnish");
		Languages.add("Flemmish");
		Languages.add("Fon");
		Languages.add("French");
		Languages.add("Ganda");
		Languages.add("Georgian");
		Languages.add("Greek");
		Languages.add("Greek");
		Languages.add("Guaraní");
		Languages.add("Hai||om");
		Languages.add("Hassaniyya Arabic");
		Languages.add("Hausa");
		Languages.add("Hausa");
		Languages.add("Hindi");
		Languages.add("Hungarian");
		Languages.add("Icelandic");
		Languages.add("Irish");
		Languages.add("Island Carib");
		Languages.add("Italian");
		Languages.add("Japanese");
		Languages.add("Javanese");
		Languages.add("Kalanga");
		Languages.add("Kazah");
		Languages.add("Khmer, Central");
		Languages.add("Kikuyu");
		Languages.add("Kirgyz");
		Languages.add("Koongo");
		Languages.add("Korean");
		Languages.add("Korean");
		Languages.add("Lao");
		Languages.add("Latvian");
		Languages.add("Lenca");
		Languages.add("Liberia Kpelle");
		Languages.add("Lithuanian");
		Languages.add("Luba-Kasai");
		Languages.add("Luxembourgeois");
		Languages.add("Macedonian");
		Languages.add("Makhuwa");
		Languages.add("Malagasy");
		Languages.add("Malay");
		Languages.add("Maltese");
		Languages.add("Mandarin Chinese");
		Languages.add("Mandinka");
		Languages.add("Maninka");
		Languages.add("Maninka");
		Languages.add("Manza");
		Languages.add("Maori");
		Languages.add("Mapudungun");
		Languages.add("Mayan");
		Languages.add("Mbere ");
		Languages.add("Mbundu");
		Languages.add("Miskito");
		Languages.add("Mongolian, Halh");
		Languages.add("MÒORÉ");
		Languages.add("Nahuatl");
		Languages.add("Nepali");
		Languages.add("Ngabere");
		Languages.add("Ngambay");
		Languages.add("Norwegian, Bokmaal");
		Languages.add("Nyanja");
		Languages.add("Nyanja");
		Languages.add("Oromo");
		Languages.add("Panjabi, Western");
		Languages.add("Papuan");
		Languages.add("Pashto");
		Languages.add("Pipil");
		Languages.add("Polish");
		Languages.add("Portuguese");
		Languages.add("Pulaar");
		Languages.add("Quechua, South Bolivian");
		Languages.add("Rarotongan");
		Languages.add("Romanian");
		Languages.add("Romanian");
		Languages.add("Rundi");
		Languages.add("Russian");
		Languages.add("Rwanda");
		Languages.add("Samoan");
		Languages.add("Samoan");
		Languages.add("Senoufo, Cebaara");
		Languages.add("Serbian");
		Languages.add("Shona");
		Languages.add("Sinhala");
		Languages.add("Slovak");
		Languages.add("Slovenian");
		Languages.add("Somali");
		Languages.add("Sotho, Southern");
		Languages.add("South Bolivian Quechuan");
		Languages.add("Spanish");
		Languages.add("Standard German");
		Languages.add("Sukuma");
		Languages.add("Swedish");
		Languages.add("Swiss German");
		Languages.add("Tagalog");
		Languages.add("Tajiki");
		Languages.add("Temne");
		Languages.add("Tetun");
		Languages.add("Thai");
		Languages.add("Tigrinya");
		Languages.add("Tongan");
		Languages.add("Tupi-Guarani");
		Languages.add("Tupi-Guaraní ");
		Languages.add("Turkish");
		Languages.add("Turkmen");
		Languages.add("Ukrainian");
		Languages.add("Uzbek");
		Languages.add("Vietnamese");
		Languages.add("Wayuu");
		Languages.add("Wolof");
		Languages.add("Zulu");


		
		
		return Languages;
	}
}
