<select name="motherTongue" class="required input_field">
	<option selected>Select Mother Tongue</option>
	<option>Afrikaans</option>
	<option>Albanian</option>
	<option>Amharic</option>
	<option>Arabic</option>
	<option>Armenian</option>
	<option>Basque</option>
	<option>Bengali</option>
	<option>Byelorussian</option>
	<option>Burmese</option>
	<option>Bulgarian</option>
	<option>Catalan</option>
	<option>Czech</option>
	<option>Chinese</option>
	<option>Croatian</option>
	<option>Danish</option>
	<option>Dari</option>
	<option>Dzongkha</option>
	<option>Dutch</option>
	<option>English</option>
	<option>Esperanto</option>
	<option>Estonian</option>
	<option>Faroese</option>
	<option>Farsi</option>
	<option>Finnish</option>
	<option>French</option>
	<option>Gaelic</option>
	<option>Galician</option>
	<option>German</option>
	<option>Greek</option>
	<option>Hebrew</option>
	<option>Hindi</option>
	<option>Hungarian</option>
	<option>Icelandic</option>
	<option>Indonesian</option>
	<option>Inuktitut (Eskimo)</option>
	<option>Italian</option>
	<option>Japanese</option>
	<option>Khmer</option>
	<option>Korean</option>
	<option>Kurdish</option>
	<option>Laotian</option>
	<option>Latvian</option>
	<option>Lappish</option>
	<option>Lithuanian</option>
	<option>Macedonian</option>
	<option>Malay</option>
	<option>Maltese</option>
	<option>Nepali</option>
	<option>Norwegian</option>
	<option>Pashto</option>
	<option>Polish</option>
	<option>Portuguese</option>
	<option>Romanian</option>
	<option>Russian</option>
	<option>Scots</option>
	<option>Serbian</option>
	<option>Slovak</option>
	<option>Slovenian</option>
	<option>Somali</option>
	<option>Spanish</option>
	<option>Swedish</option>
	<option>Swahili</option>
	<option>Tagalog-Filipino</option>
	<option>Tajik</option>
	<option>Tamil</option>
	<option>Thai</option>
	<option>Tibetan</option>
	<option>Tigrinya</option>
	<option>Tongan</option>
	<option>Turkish</option>
	<option>Turkmen</option>
	<option>Ucrainian</option>
	<option>Urdu</option>
	<option>Uzbek</option>
	<option>Vietnamese</option>
	<option>Welsh</option>
	
</select>